# This is a basic workflow to help you get started with Actions

name: Deploy Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the stage branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Generate deployment package
        run: git archive -v -o deploy.zip --format=zip HEAD
        
      # Uses forked version of einaregilsson/beanstalk-deploy@v14 with fix for parentheses
      # in the application name.
      - name: Deploy to EB
        uses: noahshuart/beanstalk-deploy@be925a70aefcb94d4bc8bebbfb519d541170d9aa
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Unstuq (Production)
          environment_name: unstuq-production-env
          version_label: ${{ github.run_id }}
          version_description: ${{ github.SHA }}
          region: us-east-2
          deployment_package: deploy.zip

